sudo: required

language: java

services:
 - docker

before_install:
 - docker build -t green .
 - docker run -d -p 127.0.0.1:80:4567 green /bin/sh -c "ant;"
 - docker ps -a
 - docker run green -c "ant test;"

script:
 - ant;
 - ant test;
